# fly.toml app configuration file generated for docs-template-test on 2025-09-12T12:27:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docs-template-test'
primary_region = 'fra'

[build]


[deploy]
  strategy = 'bluegreen'
  wait_timeout = '15m0s'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
