// This file is generated by icon spritesheet generator

export const iconNames = [
	"Zap",
	"X",
	"TriangleAlert",
	"Sun",
	"SunMoon",
	"Rocket",
	"Moon",
	"Menu",
	"Info",
	"Github",
	"Ghost",
	"ClipboardCopy",
	"ClipboardCheck",
	"ChevronRight",
	"ChevronDown",
] as const

export type IconName = (typeof iconNames)[number]
