// This file is generated by icon spritesheet generator

export const iconNames = [
	"Zap",
	"X",
	"TriangleAlert",
	"Trash2",
	"Sun",
	"SunMoon",
	"Search",
	"Rocket",
	"Moon",
	"Menu",
	"Info",
	"Hash",
	"Github",
	"Ghost",
	"Folder",
	"FileText",
	"ExternalLink",
	"Clock",
	"ClipboardCopy",
	"ClipboardCheck",
	"ChevronRight",
	"ChevronDown",
	"ArrowRight",
	"ArrowLeft",
] as const

export type IconName = (typeof iconNames)[number]
